// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeTracker.Database;

#nullable disable

namespace OfficeTracker.Migrations
{
    [DbContext(typeof(OfContext))]
    [Migration("20250928160557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OfficeTracker.Database.Models.DbGeneral", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBeenDayCounted")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HomeOfficeDays")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("OfficeDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("general");
                });

            modelBuilder.Entity("OfficeTracker.Database.Models.DbPlannableDay", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("plannable_days");
                });
#pragma warning restore 612, 618
        }
    }
}
