// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeTracker.Database;

#nullable disable

namespace OfficeTracker.Migrations
{
    [DbContext(typeof(OtContext))]
    partial class OtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OfficeTracker.Database.Models.DbPlannableDay", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("plannable_days");
                });

            modelBuilder.Entity("OfficeTracker.Database.Models.DbUserSettings", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HomeOfficeDayCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("HomeOfficeDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("HomeOfficeTargetQuoted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("OfficeDayCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("OfficeDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("OfficeTargetQuoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("user_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
