// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeTracker.Infrastructure.Database;

#nullable disable

namespace OfficeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(OtContext))]
    [Migration("20251110195744__holidays")]
    partial class _holidays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("OfficeTracker.Infrastructure.Database.Models.HolidayModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("holidays");
                });

            modelBuilder.Entity("OfficeTracker.Infrastructure.Database.Models.PlannableDayModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("plannable_days");
                });

            modelBuilder.Entity("OfficeTracker.Infrastructure.Database.Models.UserSettingsModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HomeOfficeDayCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("HomeOfficeDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("HomeOfficeTargetQuoted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("OfficeDayCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("OfficeDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("OfficeTargetQuoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("user_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
