namespace OfficeTracker.Services.Config.Models;

/// <summary>
/// Represents local configuration settings for the application window, including position and size.
/// This class implements the INotifyPropertyChanged interface to enable property change notifications.
/// </summary>
public sealed class LocalConfig : INotifyPropertyChanged
{
	#region DATABASE PATH

	/// <summary>
	/// Field representing the file path to the application's database.
	/// This path is constructed by combining the application's data directory and a predefined database file name.
	/// Changes to the corresponding property trigger a property change notification.
	/// </summary>
	private string _databasePath
		= PathHelper.AppDataPath;

	/// <summary>
	/// Gets or sets the file path to the database used by the application.
	/// This path is generated by combining the application's data directory and the database name.
	/// Updates trigger a property change notification.
	/// </summary>
	public string DatabasePath
	{
		get => _databasePath;
		set
		{
			if (value == _databasePath) return;
			_databasePath = value;
			OnPropertyChanged();
		}
	}

	#endregion

	#region LANGUAGE

	/// <summary>
	/// Stores the current language setting for the application.
	/// This determines the language used within the user interface and other language-dependent features.
	/// </summary>
	private Language _language = Language.English;

	/// <summary>
	/// Specifies the language preference for the application. This setting determines
	/// the language in which the application's user interface will be displayed.
	/// </summary>
	public Language Language
	{
		get => _language;
		set
		{
			if(value == _language) return;
			_language = value;
			OnPropertyChanged();
		}
	}

	#endregion

	#region WINDOW SIZE/POSITION

	/// <summary>
	/// Indicates whether the application should preserve and restore the window's position and size
	/// during application restarts. If set to true, the window's current position and dimensions
	/// are saved and reapplied on subsequent launches.
	/// </summary>
	private bool _rememberWindowPositionSize = true;

	/// <summary>
	/// Determines whether the application window's position and size should be remembered across sessions.
	/// When set to true, the current window dimensions and location are saved and restored upon reopening the application.
	/// Changing this property triggers a property change notification.
	/// </summary>
	public bool RememberWindowPositionSize
	{
		get => _rememberWindowPositionSize;
		set
		{
			if (value == _rememberWindowPositionSize) return;
			_rememberWindowPositionSize = value;
			OnPropertyChanged();
		}
	}

	#region WINDOW POSITION

	/// <summary>
	/// Stores the current position of the application window as a ConfigIntVector object.
	/// The X and Y components represent the horizontal and vertical positions of the window on the screen, respectively.
	/// Updated when the window is repositioned and triggers a property change notification.
	/// </summary>
	private ConfigIntVector _windowPosition
		= new(MainWindowData.WindowPosition.X, MainWindowData.WindowPosition.Y);

	/// <summary>
	/// Represents the current position of the application window as a ConfigIntVector object.
	/// Allows getting or setting the horizontal (X) and vertical (Y) screen coordinates of the window.
	/// Updates the backing field and triggers a property change notification when modified.
	/// </summary>
	public ConfigIntVector WindowPosition
	{
		get => _windowPosition;
		set
		{
			if (value.X == _windowPosition.X && value.Y == _windowPosition.Y) return;
			_windowPosition = value;
			OnPropertyChanged();
		}
	}

	#endregion

	#region WINDOW SIZE

	/// <summary>
	/// Represents the dimensions of the application window as a ConfigIntVector object.
	/// The X and Y components correspond to the width and height of the window in pixels, respectively.
	/// This value is initialized based on the MainWindowData.WindowSize and updated
	/// when the window size changes, triggering a property change notification.
	/// </summary>
	private ConfigIntVector _windowSize
		= new((int)MainWindowData.WindowSize.Width, (int)MainWindowData.WindowSize.Height);

	/// <summary>
	/// Provides the size of the application window as a ConfigIntVector object.
	/// The X component represents the width of the window in pixels, and the Y component represents the height in pixels.
	/// This property is monitored for changes and triggers a property change notification when updated.
	/// </summary>
	public ConfigIntVector WindowSize
	{
		get => _windowSize;
		set
		{
			if (value.X == _windowSize.X && value.Y == _windowSize.Y) return;
			_windowSize = value;
			OnPropertyChanged();
		}
	}

	#endregion

	#endregion

	#region EVENT

	/// <summary>
	/// An event used to notify subscribers when a property value changes within the LocalConfig class.
	/// Triggered any time a property setter calls the OnPropertyChanged method, passing the name of the updated property.
	/// Commonly utilized for data-binding scenarios in MVVM architecture to reflect UI changes dynamically.
	/// </summary>
	public event PropertyChangedEventHandler? PropertyChanged;

	/// <summary>
	/// Notifies listeners that a property value has changed.
	/// </summary>
	private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
		=> PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

	#endregion
}
